server:
  port: 8888
  # 服务器外网ip
  extranet: 127.0.0.1
  ssl:
    key-password: 123456
    key-store: classpath:spring.keystore
    key-alias: spring

spring:
  application:
        name: live
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面

stream:
  converter: ffmpeg
  transport: original






